services:
  postiz-postgres:
    image: postgres:alpine # 16.4
    container_name: postiz-postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postiz-local-pwd
      POSTGRES_USER: postiz-local
      POSTGRES_DB: postiz-db-local
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - postiz-network
  postiz-redis:
    image: redis:alpine # 7.4.0
    container_name: postiz-redis
    restart: always
    ports:
      - 6379:6379
    networks:
      - postiz-network
  postiz-minio:
    image: quay.io/minio/minio
    container_name: postiz-minio
    command: server /data --console-address ":9001"
    ports:
      - '9000:9000'
      - '9001:9001'
    networks:
      - postiz-network
    volumes:
      - minio:/data
    environment:
      - MINIO_ROOT_USER=postiz-minio
      - MINIO_ROOT_PASSWORD=postiz-minio-pwd

  postiz-pg-admin:
    image: dpage/pgadmin4
    container_name: postiz-pg-admin
    restart: always
    ports:
      - 8081:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    networks:
      - postiz-network
  postiz-redisinsight:
    image: redis/redisinsight:latest #
    container_name: postiz-redisinsight
    links:
      - postiz-redis
    ports:
      - "5540:5540"
    volumes:
      - redisinsight:/data
    networks:
      - postiz-network
    restart: always

volumes:
  redisinsight:
  minio:
    driver: local
  postgres-volume:
    external: false

networks:
  postiz-network:
    external: false
